### ISSUE TITLE
About the result figure.

### ISSUE THREAD

**Issue by cientgu** [ChristophReich1996/Semantic_Pyramid_for_Image_Generation#2]
Thank you for the project! What's the meaning about the results figure shown in your readme? Is it the output image from the training procedure or? And why some of the results look good and some looks strange?

**Comment by ChristophReich1996** [comment]
Hi, thanks for your interest! The figure showes random samples of the generator for different stages of the classification model. Since I only have limited computing power available I was only able to train for approximately 48h on one Nvidia Tesla V100. The original paper, however, trained 48h on a big Dragonfish TPU. I think that the samples, shown in the README, are that bad because the network needs to train much longer. If you achieve better results with longer training and more commute resources let me know.

**Comment by cientgu** [comment]
Thank you for your reply and your reimplementation! I will tell you if i get a better results.
